version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .postgres.env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  dev:
    env_file:
      - .env
    container_name: nestjs_api_dev
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    restart: unless-stopped
#  prod:
#    container_name: nestjs_api_prod
#    image: nestjs-api-prod:1.0.0
#    build:
#      context: .
#      target: production
#      dockerfile: ./Dockerfile
#    command: npm run start:prod
#    ports:
#      - 3000:3000
#      - 9229:9229
#    networks:
#      - nesjs-network
#    volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules
#    restart: unless-stopped

volumes:
  db:
    driver: local
